# Generated by Django 5.2.1 on 2025-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
