# Generated by Django 5.2.1 on 2025-06-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
