# Generated by Django 6.0 on 2026-05-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_customuser_age_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
