# Generated by Django 6.0 on 2026-06-17 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_remove_customuser_age_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('pt', 'Portuguese'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=10)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('Africa/Lagos', 'Africa/Lagos'), ('Africa/Nairobi', 'Africa/Nairobi'), ('Africa/Johannesburg', 'Africa/Johannesburg'), ('Africa/Accra', 'Africa/Accra'), ('Africa/Cairo', 'Africa/Cairo'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Berlin', 'Europe/Berlin'), ('America/New_York', 'America/New_York'), ('America/Chicago', 'America/Chicago'), ('America/Denver', 'America/Denver'), ('America/Los_Angeles', 'America/Los_Angeles'), ('Asia/Dubai', 'Asia/Dubai'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Asia/Shanghai', 'Asia/Shanghai'), ('Asia/Kolkata', 'Asia/Kolkata')], default='UTC', max_length=50)),
                ('base_currency', models.CharField(choices=[('NGN', 'Naira (NGN)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('JPY', 'Japanese Yen (JPY)'), ('KES', 'Kenyan Shilling (KES)'), ('ZAR', 'South African Rand (ZAR)'), ('GHS', 'Ghanaian Cedi (GHS)')], default='NGN', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
