# Generated by Django 6.0 on 2026-05-04 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySpendingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_plan', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=100)),
                ('budget_amount', models.PositiveIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSpendingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_plan', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=100)),
                ('budget_amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('savings_amount', models.PositiveIntegerField()),
                ('savings_reached_amount', models.PositiveIntegerField(default=0)),
                ('savings_reached', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Past Deadline', 'Past Deadline'), ('Completed', 'Completed')], max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('transaction_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_savings', models.BooleanField(default=False)),
                ('savings_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('savings_note', models.TextField(blank=True, max_length=500, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.category')),
                ('savings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.savingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('next_due_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.transaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='Tracker_cat_user_id_6d6512_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category_name'),
        ),
        migrations.AddIndex(
            model_name='categoryspendinglimit',
            index=models.Index(fields=['user', 'category'], name='Tracker_cat_user_id_49deca_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryspendinglimit',
            index=models.Index(fields=['user', 'budget_plan'], name='Tracker_cat_user_id_d90621_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryspendinglimit',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'budget_plan'), name='unique_user_category_spending_limit'),
        ),
        migrations.AddIndex(
            model_name='generalspendinglimit',
            index=models.Index(fields=['user', 'budget_plan'], name='Tracker_gen_user_id_227d22_idx'),
        ),
        migrations.AddIndex(
            model_name='savingplan',
            index=models.Index(fields=['user', 'status'], name='Tracker_sav_user_id_5b10ba_idx'),
        ),
        migrations.AddIndex(
            model_name='savingplan',
            index=models.Index(fields=['deadline'], name='Tracker_sav_deadlin_0e9dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='Tracker_tra_user_id_3dc28b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='Tracker_tra_user_id_0cd804_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_deleted'], name='Tracker_tra_is_dele_377f77_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'active'], name='Tracker_rec_user_id_caa98a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['next_due_date'], name='Tracker_rec_next_du_9b81c7_idx'),
        ),
    ]
