# Generated by Django 5.2.1 on 2025-06-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_category_user_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='tag',
        ),
    ]
