# Generated by Django 6.0 on 2026-06-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_transaction_currency_currencyexchangerate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiptProcessingJob',
        ),
    ]
