# Generated by Django 6.0 on 2026-06-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_delete_receiptprocessingjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
