# Generated by Django 5.2.1 on 2025-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_category_tag_subcategory_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
