# Generated by Django 6.0 on 2026-06-18 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_alter_recurringtransaction_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.category'),
        ),
    ]
