# Generated by Django 5.2.1 on 2025-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_alter_category_tag_alter_subcategory_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
