# Generated by Django 5.2.4 on 2026-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_alter_recurringtransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingplan',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
