# Generated by Django 5.2.4 on 2026-06-18 21:25

from django.conf import settings
from django.db import migrations, models


def copy_budget_data(apps, schema_editor):
    GeneralSpendingLimit = apps.get_model("Tracker", "GeneralSpendingLimit")
    CategorySpendingLimit = apps.get_model("Tracker", "CategorySpendingLimit")

    for obj in GeneralSpendingLimit.objects.all():
        obj.amount = obj.budget_amount
        obj.period = obj.budget_plan
        obj.name = f"{obj.budget_plan} Budget"
        obj.save()

    for obj in CategorySpendingLimit.objects.all():
        obj.amount = obj.budget_amount
        obj.period = obj.budget_plan
        obj.name = f"{obj.budget_plan} Budget"
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_savingplan_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoryspendinglimit',
            name='unique_user_category_spending_limit',
        ),
        migrations.RemoveIndex(
            model_name='categoryspendinglimit',
            name='Tracker_cat_user_id_d90621_idx',
        ),
        migrations.RemoveIndex(
            model_name='generalspendinglimit',
            name='Tracker_gen_user_id_227d22_idx',
        ),
        migrations.AddField(
            model_name='categoryspendinglimit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='categoryspendinglimit',
            name='name',
            field=models.CharField(default='My Budget', max_length=100),
        ),
        migrations.AddField(
            model_name='categoryspendinglimit',
            name='period',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=100),
        ),
        migrations.AddField(
            model_name='generalspendinglimit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='generalspendinglimit',
            name='name',
            field=models.CharField(default='My Budget', max_length=100),
        ),
        migrations.AddField(
            model_name='generalspendinglimit',
            name='period',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=100),
        ),
        migrations.RunPython(copy_budget_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='categoryspendinglimit',
            name='budget_amount',
        ),
        migrations.RemoveField(
            model_name='categoryspendinglimit',
            name='budget_plan',
        ),
        migrations.RemoveField(
            model_name='generalspendinglimit',
            name='budget_amount',
        ),
        migrations.RemoveField(
            model_name='generalspendinglimit',
            name='budget_plan',
        ),
        migrations.AddIndex(
            model_name='categoryspendinglimit',
            index=models.Index(fields=['user', 'period'], name='Tracker_cat_user_id_bbd8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='generalspendinglimit',
            index=models.Index(fields=['user', 'period'], name='Tracker_gen_user_id_4fb8d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryspendinglimit',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'period'), name='unique_user_category_budget'),
        ),
    ]
