# Generated by Django 5.2.1 on 2025-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_transaction_sub_category_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50),
        ),
    ]
