# Generated by Django 5.2.1 on 2025-06-03 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0012_categorybudget_generalbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryBudget',
            new_name='CategorySpendingLimit',
        ),
        migrations.RenameModel(
            old_name='GeneralBudget',
            new_name='GeneralSpendingLimit',
        ),
    ]
