# Generated by Django 5.2.1 on 2025-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0013_rename_categorybudget_categoryspendinglimit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
