# Generated by Django 5.2.1 on 2025-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0015_transaction_add_savings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='savings_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
