# Generated by Django 5.2.1 on 2025-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0016_alter_transaction_savings_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='savings_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
