# Generated by Django 5.2.1 on 2025-06-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0018_alter_transaction_savings_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='savings_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
