# Generated by Django 5.2.1 on 2025-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0019_alter_transaction_savings_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
