# Generated by Django 5.2.1 on 2025-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0021_savingplan_alter_transaction_savings_delete_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='savings_reached_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savingplan',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Past Deadline', 'Past Deadline'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
