# Generated by Django 5.2.4 on 2025-08-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0022_alter_savingplan_savings_reached_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
