# Generated by Django 5.2.4 on 2025-08-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0024_transaction_recurring_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tracker.transaction'),
            preserve_default=False,
        ),
    ]
