# Generated by Django 5.2.4 on 2025-08-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0025_recurringtransaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
    ]
