# Generated by Django 6.0 on 2026-05-01 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0027_rename_date_transaction_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generalspendinglimit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='Tracker_cat_user_id_6d6512_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryspendinglimit',
            index=models.Index(fields=['user', 'category'], name='Tracker_cat_user_id_49deca_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryspendinglimit',
            index=models.Index(fields=['user', 'budget_plan'], name='Tracker_cat_user_id_d90621_idx'),
        ),
        migrations.AddIndex(
            model_name='generalspendinglimit',
            index=models.Index(fields=['user', 'budget_plan'], name='Tracker_gen_user_id_227d22_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'active'], name='Tracker_rec_user_id_caa98a_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['next_due_date'], name='Tracker_rec_next_du_9b81c7_idx'),
        ),
        migrations.AddIndex(
            model_name='savingplan',
            index=models.Index(fields=['user', 'status'], name='Tracker_sav_user_id_5b10ba_idx'),
        ),
        migrations.AddIndex(
            model_name='savingplan',
            index=models.Index(fields=['deadline'], name='Tracker_sav_deadlin_0e9dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='Tracker_tra_user_id_3dc28b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='Tracker_tra_user_id_0cd804_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_deleted'], name='Tracker_tra_is_dele_377f77_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category_name'),
        ),
        migrations.AddConstraint(
            model_name='categoryspendinglimit',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'budget_plan'), name='unique_user_category_spending_limit'),
        ),
    ]
